import { Mission, User } from '@/types';

export const createDefaultUser = (): User => ({
  id: 'user_1',
  username: 'EcoWarrior',
  points: 0,
  xp: 0,
  level: 1,
  streak: 0,
  badges: [],
  upvotedMissionIds: [],
  dailyReportCount: {},
  createdAt: new Date().toISOString(),
});

export const createSeedMissions = (): Mission[] => [
  {
    id: 'mission_1',
    title: 'Littered Park Entrance',
    description: 'Fast food containers and plastic bottles scattered near the main entrance. Heavy foot traffic area that needs attention.',
    status: 'needs',
    coords: { lat: 37.7749, lng: -122.4194 },
    trashType: 'bags',
    estBags: 3,
    reporterId: 'user_2',
    upvotes: 2,
    photosBefore: ['https://images.pexels.com/photos/9324305/pexels-photo-9324305.jpeg?auto=compress&cs=tinysrgb&w=800'],
    photosAfter: [],
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'mission_2',
    title: 'Construction Debris',
    description: 'Old concrete pieces and metal scraps left behind from recent construction work. Blocking pedestrian walkway.',
    status: 'progress',
    coords: { lat: 37.7849, lng: -122.4094 },
    trashType: 'construction',
    estBags: 8,
    reporterId: 'user_3',
    claimedByUserId: 'user_1',
    upvotes: 5,
    photosBefore: ['https://images.pexels.com/photos/416978/pexels-photo-416978.jpeg?auto=compress&cs=tinysrgb&w=800'],
    photosAfter: [],
    createdAt: '2024-01-14T15:45:00Z',
    updatedAt: '2024-01-15T09:20:00Z',
  },
  {
    id: 'mission_3',
    title: 'Beach Cleanup Success',
    description: 'Plastic bottles and food wrappers along the shoreline. Great community effort resulted in a clean beach!',
    status: 'cleaned',
    coords: { lat: 37.7649, lng: -122.4394 },
    trashType: 'bags',
    estBags: 5,
    reporterId: 'user_4',
    claimedByUserId: 'user_5',
    upvotes: 12,
    photosBefore: ['https://images.pexels.com/photos/2547565/pexels-photo-2547565.jpeg?auto=compress&cs=tinysrgb&w=800'],
    photosAfter: ['https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg?auto=compress&cs=tinysrgb&w=800'],
    createdAt: '2024-01-13T08:15:00Z',
    updatedAt: '2024-01-14T16:30:00Z',
  },
  {
    id: 'mission_4',
    title: 'Illegal Dumping Site',
    description: 'Large appliances and furniture dumped in vacant lot. Requires special disposal arrangements.',
    status: 'needs',
    coords: { lat: 37.7949, lng: -122.4294 },
    trashType: 'illegal_dump',
    estBags: 15,
    reporterId: 'user_6',
    upvotes: 1,
    photosBefore: ['https://images.pexels.com/photos/3737398/pexels-photo-3737398.jpeg?auto=compress&cs=tinysrgb&w=800'],
    photosAfter: [],
    createdAt: '2024-01-15T12:00:00Z',
    updatedAt: '2024-01-15T12:00:00Z',
  },
  {
    id: 'mission_5',
    title: 'Roadside Cleanup',
    description: 'Mixed trash along busy road - cans, bottles, paper. Moderate cleanup job for dedicated volunteer.',
    status: 'progress',
    coords: { lat: 37.7549, lng: -122.4494 },
    trashType: 'misc',
    estBags: 4,
    reporterId: 'user_7',
    claimedByUserId: 'user_8',
    upvotes: 3,
    photosBefore: ['https://images.pexels.com/photos/9324316/pexels-photo-9324316.jpeg?auto=compress&cs=tinysrgb&w=800'],
    photosAfter: [],
    createdAt: '2024-01-14T11:20:00Z',
    updatedAt: '2024-01-15T07:45:00Z',
  },
];